server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/profile/**

        - id: vacancy-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/vacancy/**

        - id: listing-vacancies-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/vacancies/**

        - id: applications-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/responses/**

        - id: chat-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/chat/**

      # ????????? ?????? ? http://localhost:3000 ?????? ?? gateway
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

jwt:
  secret: ${jwt_secret}